info:
  component: Hub Api
  project:
    name: Hub-hub
    version: 0.0.1-SNAPSHOT

server:
  port: 8077
  contextPath: /Hub-hub
  tomcat:
    basedir: /tmp/tomcat

management:
  security:
    enabled: false

spring:
  application:
    name: Hub-api

  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  logging:
  level:
    org:
      hibernate:
        type: trace

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

    tomcat:
      max-wait: 60000
      initial-size: 10
      max-active: 150
      test-on-borrow: true
